micronaut:
  application:
    name: inventory
  server:
    port: 8081
  caches:
    external-api-cache:
      maximumSize: 20
      expire-after-access: 10s
      expire-after-write: 10s
  http:
    services:
      exchangeratesapi:
        #        read-timeout: 1s
        #        connect-timeout: 1s
        followRedirects: false
        pool:
          enabled: true
        urls:
          - https://api.exchangeratesapi.io
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

# Management API
endpoints:
  all:
    enabled: true
    sensitive: false
